title: Hacking In Progress
description: >-
  A glimpse into the mind of a pretty ordinary software engineer.
  May include Ruby, JavaScript, AWS, and whatever else I feel like.
  May also include dad jokes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andrewweinstein.dev"
github_username:  ajw725
linkedin_username: ajw725

# Build settings
theme: minima

plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
